theme: jekyll-theme-minimal
title: Energy Crisis in Alzheimerâ€™s Mouse Brain
description: The website of group InsertCoolTeamNameAda2025 for the Xenium's Alzheimers disease data analysis
show_downloads: True
navigation:
  - title: Home
    url: home.md
  - title: Example
    url: example.md
  - title: Dataset
    url: data.md
  - title: RQ1 Spatial analysis
    url: spatial_analysis.md
  - title: RQ2 Temporal analysis
    url: temporal_analysis.md
  - title: RQ3 Cell type
    url: cell_type.md
  - title: Team
    url: team.md


