theme: jekyll-theme-minimal
title: InsertCoolTeamNameAda2025 website
description: The website of group InsertCoolTeamNameAda2025 for the Xenium's Alzheimers disease data analysis
show_downloads: True
navigation:
  - title: Home
    url: README
  - title: Example
    url: example
